version: '3.3'

services:
  php-app:
    build: Docker
    container_name: php-app
    user: $USER_ID:$GROUP_ID
    volumes:
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
      - "./:/var/www/"
    tty: true
    ports:
      - "8000:8000"
